### ISSUE TITLE
alpha /departments showing up in GA under OEM tag

### ISSUE THREAD

**Issue by laurenancona** [CityOfPhiladelphia/phila.gov-theme#42]
alpha.phila.gov/departments/ is somehow showing up in GA under `Office of Emergency Management`, so that page probably shouldn't be getting `update date` and `department owner` at all.

**Comment by karissademi** [comment]
Thanks. This will be fixed early next week.

**Comment by karissademi** [comment]
Fixed in https://github.com/CityOfPhiladelphia/phila.gov-theme/commit/2a1a2e2c7e0f0227658618d830360011944c32ca
